-- DROP TABLE aluno;

SET SERVEROUTPUT ON;

CREATE TABLE alunos(
    id_aluno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(80) NOT NULL,
    idade NUMBER(3)
);

CREATE OR REPLACE PACKAGE pkg_alunos AS 
    PROCEDURE proc_inserir_aluno(p_nome VARCHAR2, p_idade NUMBER);
    FUNCTION func_contar_alunos RETURN NUMBER;
END pkg_alunos;

CREATE OR REPLACE PACKAGE BODY pkg_alunos AS
    PROCEDURE proc_inserir_aluno(p_nome VARCHAR2, p_idade NUMBER) IS
        BEGIN
        INSERT INTO alunos(nome, idade)
        VALUES (p_nome, p_idade);
        COMMIT;
    END proc_inserir_aluno;
    
    FUNCTION func_contar_alunos
        RETURN NUMBER IS
            v_total NUMBER;
        BEGIN
            SELECT COUNT(*) INTO v_total FROM alunos;
        RETURN v_total;
   END;
END pkg_alunos;

--- Usando o Pacote
BEGIN
    pkg_alunos.proc_inserir_aluno('Júlia', 18);
    pkg_alunos.proc_inserir_aluno('Paulo', 23);
END;

DECLARE
    v_soma NUMBER;
BEGIN
    v_soma := pkg_alunos.func_contar_alunos();
    dbms_output.put_line('Total de alunos: ' || v_soma); 
END;